# Generated by Django 5.2.6 on 2025-09-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_author_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, related_name='links', to='blog.link'),
        ),
    ]
