# Generated by Django 5.2.6 on 2025-09-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_link_post_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='links',
        ),
    ]
