# Generated by Django 5.2.6 on 2025-09-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_link_title_alter_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='links', to='blog.link'),
        ),
    ]
