# Generated by Django 5.2.6 on 2025-09-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='Default.png', upload_to='author_image/'),
        ),
    ]
